run vlfeat/toolbox/vl_setup
run matconvnet/matlab/vl_setupnn

try
  vl_nnconv(single(1),single(1),[]) ;
catch
  warning('MatConvNet not compiled, attempting to fix...') ;
  copyfile(...
    'matconvnet/matlab/src/vl_nnconv.cu', ...
    'matconvnet/matlab/src/vl_nnconv.cpp') ;
  mex('matconvnet/matlab/src/vl_nnconv.cpp', ...
    'matconvnet/matlab/src/bits/im2col.cpp', ...
    '-Imatconvnet/matlab/src',...
    '-lmwblas') ;
end
