name ?= practical-category-detection
ver ?= 2018a

code=\
boxinclusion.m \
boxoverlap.m \
boxsuppress.m \
detect.m \
detectAtMultipleScales.m \
evalDetections.m \
evaluateModel.m \
exercise1.m \
exercise2.m \
exercise3.m \
exercise4.m \
exercise5.m \
extract.m \
loadData.m \
setup.m \
README.md \
vlfeat \
matconvnet

doc=\
doc/images \
doc/instructions.html

data=\
data/signs.mat \
data/signs-sample-image.jpg \
data/signs

include extra/practical/Makefile
