name ?= practical-category-detection
ver ?= 2019a-pytorch

code=\
lab.py \
practical.ipynb \
README.md

doc=

data=\
data/signs-data.mat \
data/mandatory.jpg \
data/signs \
data/cover.jpeg

include extra/practical/Makefile
